services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    user: "1000:1000"
    network_mode: "host"
    group_add:
    - "105" #change to your group
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 # change this to your GPU for hardware decoding
    volumes:
      - /docker/jellyfin/config:/config
      - /docker/jellyfin/cache:/cache
      - /docker/data:/data
      - /docker/jellyfin/fonts:/usr/local/share/fonts/custom:ro
    environment:
      - JELLYFIN_PublishedServerUrl=http://'YOUR-IP-HERE'
      - TZ=Europe/Belgrade # change to your timezone
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Belgrade # change to your timezone
      - PORT=5055
    ports:
      - "5055:5055"
    volumes:
      - /docker/jellyseerr/config:/app/config
      - /docker/data:/data
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Belgrade # change to your timezone
    volumes:
      - /docker/radarr/config:/config
      - /docker/data:/data
    ports:
      - "7878:7878"
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Belgrade # change to your timezone
    volumes:
      - /docker/sonarr/config:/config
      - /docker/data:/data
    ports:
      - "8989:8989"
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Belgrade # change to your timezone
    volumes:
      - /docker/prowlarr/config:/config
      - /docker/data:/data
    ports:
      - "9696:9696"
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Belgrade
      - WEBUI_PORT=8080 # if you want to run webui on a diffrent port, change the setting bellow not this one
      - TORRENTING_PORT=6881
    volumes:
      - /docker/qbittorrent/config:/config
      - /docker/data:/data
    ports:
      - "8080:8080" #if you want to run qbittorrent on a diffrent port then 8080, change it here
      - "6881:6881"
      - "6881:6881/udp"
    restart: unless-stopped
